package com.github.com.cakevm.intellij_huff_plugin.ide.completion

import com.intellij.codeInsight.completion.CompletionParameters
import com.intellij.codeInsight.completion.CompletionProvider
import com.intellij.codeInsight.completion.CompletionResultSet
import com.intellij.codeInsight.lookup.LookupElementBuilder
import com.intellij.util.ProcessingContext

class HuffOpcodeCompletionProvider : CompletionProvider<CompletionParameters>() {
  override fun addCompletions(parameters: CompletionParameters, context: ProcessingContext, result: CompletionResultSet) {
    result.addAllElements(opcodeNames)
  }

  companion object {
    private val opcodeNames =
      kotlin
        .run {
          listOf(
            // Stack Management
            "push0",
            "push1",
            "push2",
            "push3",
            "push4",
            "push5",
            "push6",
            "push7",
            "push8",
            "push9",
            "push10",
            "push11",
            "push12",
            "push13",
            "push14",
            "push15",
            "push16",
            "push17",
            "push18",
            "push19",
            "push20",
            "push21",
            "push22",
            "push23",
            "push24",
            "push25",
            "push26",
            "push27",
            "push28",
            "push29",
            "push30",
            "push31",
            "push32",
            "pop",
            "dup1",
            "dup2",
            "dup3",
            "dup4",
            "dup5",
            "dup6",
            "dup7",
            "dup8",
            "dup9",
            "dup10",
            "dup11",
            "dup12",
            "dup13",
            "dup14",
            "dup15",
            "dup16",
            "swap1",
            "swap2",
            "swap3",
            "swap4",
            "swap5",
            "swap6",
            "swap7",
            "swap8",
            "swap9",
            "swap10",
            "swap11",
            "swap12",
            "swap13",
            "swap14",
            "swap15",
            "swap16",
            // Arithmetic and Logic
            "add",
            "sub",
            "mul",
            "div",
            "sdiv",
            "mod",
            "smod",
            "addmod",
            "mulmod",
            "exp",
            "signextend",
            "shr",
            "shl",
            "sar",
            "lt",
            "gt",
            "slt",
            "sgt",
            "eq",
            "iszero",
            "and",
            "or",
            "xor",
            "not",
            "byte",
            "sha3",
            "clz",
            // Environmental Information
            "address",
            "balance",
            "origin",
            "caller",
            "callvalue",
            "calldataload",
            "calldatasize",
            "calldatacopy",
            "codesize",
            "codecopy",
            "gasprice",
            "extcodesize",
            "extcodecopy",
            "returndatasize",
            "returndatacopy",
            "extcodehash",
            "blockhash",
            "coinbase",
            "timestamp",
            "number",
            "difficulty",
            "gaslimit",
            "prevrandao",
            "chainid",
            "basefee",
            "selfbalance",
            "blobhash",
            "blobbasefee",
            // Storage and Memory Access
            "sload",
            "sstore",
            "mload",
            "mstore",
            "mstore8",
            "msize",
            "tload",
            "tstore",
            "mcopy",
            // Flow Control
            "jump",
            "jumpi",
            "pc",
            "jumpdest",
            // System and Call-Related Opcodes
            "call",
            "callcode",
            "delegatecall",
            "staticcall",
            "create",
            "create2",
            "selfdestruct",
            // Logging
            "log0",
            "log1",
            "log2",
            "log3",
            "log4",
            // Miscellaneous
            "stop",
            "return",
            "revert",
            "invalid",
            // Gas and Cost Management
            "gas",
          )
        }
        .map { LookupElementBuilder.create(it).withCaseSensitivity(true) }
  }
}
